---
- name: java installtion on ubuntu
  hosts: all
  become: yes
  vars:
    java_version: openjdk-11-jdk
  tasks:
    - name: java installation
      ansible.builtin.apt: 
        name: "{{ java_version }}"
        update_cache: true
        state: present  