---
- name: nopcommerce installtion on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: download db packages
      ansible.builtin.apt:
        deb: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb  
    - name: aspnetcore-runtime
      ansible.builtin.apt:
        pkg:
          - aspnetcore-runtime-7.0
          - apt-transport-https
        update_cache: yes
        state: present
    - name: nginx installtion
      ansible.builtin.apt:
        name: nginx
        update_cache: yes
        state: present  
    - name: creating directory for nopcommerce
      ansible.builtin.file:
        path: /var/www/nopCommerce
        state: directory
        mode: '777'
    - name: download nopCommerce
      ansible.builtin.get_url:
        url: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.60.1/nopCommerce_4.60.1_NoSource_linux_x64.zip
        dest: /tmp/nopCommerce_4.60.1_NoSource_linux_x64.zip
        mode: '777'
    - name: install unzip
      ansible.builtin.apt:
        name: unzip 
        state: present
    - name: unzip nopcommerce
      ansible.builtin.unarchive:
        src: /tmp/nopCommerce_4.60.1_NoSource_linux_x64.zip
        dest: /var/www/nopCommerce
        remote_src: yes
    - name: creating bin dir
      ansible.builtin.file:
        path: /var/www/nopCommerce/bin
        state: directory
    - name: creating logs dir
      ansible.builtin.file:
       path: /var/www/nopCommerce/logs
       state: directory
       mode: '7777'
    - name: copying service file
      ansible.builtin.copy: 
        src: nopCommerce.service
        dest: /etc/systemd/system/nopCommerce.service
        remote_src: no
    - name: copy nginx file
      ansible.builtin.copy:
        src: default
        dest: /etc/nginx/sites-available/default
    - name: starting nopCommerce.service
      ansible.builtin.systemd: 
        name: nopCommerce.service
        daemon_reload: yes
        state: started
    - name: restart nginx
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: nginx
      

    

    



        

    

      