---
- name: nopcommerce installtion on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: download db packages
      ansible.builtin.apt:
        deb: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb  
    - name: aspnetcore-runtime
      ansible.builtin.apt:
        pkg:
          - aspnetcore-runtime-7.0
          - apt-transport-https
        update_cache: yes
        state: present
    - name: nginx installtion
      ansible.builtin.apt:
        name: nginx
        update_cache: yes
        state: present  
    - name: creating directory for nopcommerce
      ansible.builtin.file:
        path: /var/www/nopCommerce
        state: directory
        mode: '777'
    - name: download nopCommerce
      ansible.builtin.get_url:
        url:  https://github.com/nopSolutions/nopCommerce/releases/download/release-4.60.1/nopCommerce_4.60.1_NoSource_linux_x64.zip
        dest: /var/www/nopCommerce
    - name: install unzip
      ansible.builtin.apt:
        name: unzip 
        state: present
    - name: unzip nopcommerce
      ansible.builtin.unarchive:
        src: /tmp/nopCommerce_4.60.1_NoSource_linux_x64.zip
        dest:  /var/www/nopCommerce
        remote_src: yes
    - name: creating a directory and owner
      ansible.builtin.file:
        path: 
          - /etc/binstarted
          - /etc/logs
        state: directory
        mode: '7777'
    - name: Create a nginx file
      ansible.builtin.copy:
        src: sites-available
        dest: /etcnginx/sites-available/default
        owner: nopCommerce
        group: nopCommerce
    - name: Create a nopCommerce.file
      ansible.builtin.copy:
        src: nopCommerce.service
        dest: etc/systemd/system/nopCommerce.service
        owner: nopCommerce
        group: nopCommerce
    - name: start 
      ansible.builtin.systemd: 
        state: started
        name: nopCommerce
        daemon_reload: yes

    

    



        

    

      