---
- name: openmrs installtion on ubuntu22
  hosts: all
  become: yes
  tasks:
    - name: creating directory if not exist
      ansible.builtin.file:
        path: /var/lib/OpenMRS
        state: directory
    - name: Recursively change ownership of a directory
      ansible.builtin.command: chown -R tomcat:tomcat /var/lib/OpenMRS
    - name: download OpenMRS_Platform_2.5.0
      ansible.builtin.get_url:
        url: https://sourceforge.net/projects/openmrs/files/releases/OpenMRS_Platform_2.5.0/openmrs.war
        dest: /etc/openmrs.war
        mode: '777'
    - name: copying war files
      ansible.builtin.copy:
        src: /etc/openmrs.war
        dest: /opt/tomcat/webapps/openmrs.war
        remote_src: yes
    - name: changing ownership of war
      ansible.builtin.command: chown -R tomcat:tomcat /opt/tomcat/webapps/openmrs.war


        

      
    
        
    
        
        

    
        


      
      