---
- name: openmrs installtion on ubuntu22
  hosts: all
  become: yes
  tasks:
    - name: java installation
      ansible.builtin.apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: present
    - name: creating a tomcat group
      ansible.builtin.group:
        name: tomcat
        state: present
      
      