---
- name: openmrs installtion on ubuntu22
  hosts: all
  become: yes
  tasks:
    - name: java installation
      ansible.builtin.apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: present
    - name: creating a tomcat group
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: creating user in tomcat
      ansible.builtin.user:
        name: tomcat
        group: tomcat
        shell: /bin/false
        home: /opt/tomcat
        state: present
    - name: tomcat download
      ansible.builtin.get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.109/bin/apache-tomcat-7.0.109.tar.gz 
        dest: /etc/apache-tomcat-7.0.109
    - name: creating a directory for tomcat
      ansible.builtin.file:
        path: /opt/tomcat
        state: directory
    - name: unarchive tomcat
      ansible.builtin.unarchive:
        src: https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.109/bin/apache-tomcat-7.0.109.tar.gz
        dest: /opt/tomcat/
        remote_src: yes 
    - name: change tomcat group
      ansible.builtin.file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
    - name: adding executive permissions to tomcat
      ansible.builtin.command: sudo chmod -R g+r 
      register: conf
    
    
        
    
        
        

    
        


      
      