---
- name: openmrs installtion on ubuntu22
  hosts: all
  become: yes
  tasks:
    - name: java installtion
      ansible.builtin.apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: present
    - name: 