---
pool:
  name: "Azure Pipelines"
  vmImage: 'ubuntu-latest'

trigger:
  - main

stages:
  - stage: builtstage
    displayName: CI
    jobs:
      - job: Mavenjob
        displayName: Maven
        steps:
          - task: Maven@3
            inputs:
              mavenPOMFile: 'pom.xml'
              goals: package
              publishJUnitResults: yes
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              jdkVersionOption: '1.17'