---
pool: 
  name: "Azure Pipelines"
  vmImage: 'ubuntu-latest'

trigger:
  - master

jobs:
  - job: Mavenjob
    displayName: Maven
    steps:
      - task: Maven@1
        inputs:
          mavenPOMFile: 'pom.xml'
          goals: package
          publishJUnitResults: yes
          testResultsFiles: '**/TEST-*.xml'
          jdkVersionOption: '1.8'
          



