---
- name: nopcommerce installtion on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: download db packages
      ansible.builtin.apt:
        deb: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb  
    - name: aspnetcore-runtime
      ansible.builtin.apt:
        name: install aspnetcore-runtime-7.0
        update_cache: yes
        state: present
      