--- 
- name: install dotnet on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: install list of packages
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/config/ubuntu/22.10/packages-microsoft-prod.deb
        dest: /etc/packages-microsoft-prod.deb
        mode: '0777'
    - name: installing dotnet
      ansible.builtin.apt:
      pkg: 
        - dotnet-sdk-7.0
        - aspnetcore-runtime-7.0
        - microsoft-prod.deb
      update_cache: yes
      state: present


      
      
        

        