--- 
- name: install dotnet on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: install list of packages
      ansible.builtin.apt:
        deb: https://packages.microsoft.com/config/ubuntu/22.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    - name: installing list of packages
      ansible.builtin.apt:
        pkg:
          - microsoft-prod.deb
          - dotnet-sdk-7.0
          - aspnetcore-runtime-7.0
          - dotnet-runtime-7.0
      

        