---
- name: MYSQL installtion on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: install MYSQL
      ansible.builtin.apt:
        name: mysql-server
        update_cache: yes
        only_upgrade: yes
        state: present