---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx
spec: 
  containers: 
    - name: nginxpo
      image: nginx:1.23
      ports: 
        containerPort: 80
      args:
        - sleep
        - 1d
    - name: alpinepo
      image: alpine
      ports:
        - containerPort: 80
      args:
        - sleep
        - 1d 
